# Generated by Django 3.2.15 on 2022-08-28 16:46

import applications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=220)),
                ('app_url', models.CharField(max_length=220)),
                ('app_category', models.CharField(blank=True, max_length=220, null=True)),
                ('app_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('app_description', models.TextField(blank=True, null=True)),
                ('app_image_url', models.TextField(blank=True, null=True)),
                ('app_points', models.IntegerField(choices=[(50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300), (350, 350), (400, 400), (450, 450), (500, 500)], default=50)),
            ],
            options={
                'db_table': 'app',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=applications.models.image_upload_handler)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=8)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_task', to='applications.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'managed': True,
            },
        ),
    ]
